import functions as my_F


''' 

    this .py is implemented for demo.


'''

title_vae = """

GENERATED BY OUR VAE MODEL

"""


title_gans = """

GENERATED BY OUR GANs MODEL

"""

test_Str = """
1234567890
1234567890
ABCDEFGHIJKLMNOPQRSTUVwXYZ
abcdefghijklmnopqrstuvwxyz

COMP7015 Group:42  IMAGE GENERATIVE MODEL 
1: Zihao ZHAO    25418823
2: Bojie XIANG   25400444
3: Zinao SU      25434675
4: Tianchi ZHOU  25409638
5: Tianxiao ZHU  25407732


Topic 3: Open Topic
If you are interested in another AI problem that aligns 
with the course content, you may propose your own project. 

"""

# var for calculating the fid, cause it is time consuming we make it False here.
calculate_fid = False

if __name__ == '__main__':
    print("############## demo starts ##############")
    print("\n")

    print("##### Part1 SAMPLING #####")

    print("# demo GAN")
    print("loading GANs model ......")
    model_name = "gans"
    gan_g, gan_d = my_F.load_gans_model(model_name)
    print("generating GANs sample ......")
    my_F.gans_save_samples(gan_g, input_str=title_gans+test_Str, save_folder="demo_save")
    print("GAN samples saved in folder demo_save")

    # demo vae
    print("\n\n")
    print("# demo VAE")
    model_name = "vae"
    print("loading VAE model ......")
    vae_model = my_F.load_vae_model(model_name)
    print("generating VAE samples ......")
    my_F.vae_save_samples(vae_model, input_str=title_vae+test_Str, save_folder="demo_save")
    print("VAE samples saved in folder demo_save")


    # demo ddpm
    print("\n\n")
    print("# demo DDPM")
    print("loading DDPM model ......")
    model_name = "ddpm"
    ddpm_model, diffuser = my_F.load_ddpm_model(model_name)
    print("generating DDPM samples ......")
    my_F.demo_addnoise(diffuser, save_folder="demo_save")
    my_F.demo_denoise(ddpm_model, diffuser, save_folder="demo_save")
    my_F.ddpm_save_samples(ddpm_model, diffuser, modelname="ddpm", save_folder="demo_save")
    print("DDPM samples saved in folder demo_save")

    print("\n\n")



    if calculate_fid:
        print("##### Part2 FID #####")
        # calculate FID   
        my_F.save_all_FID_test_imgs()
        
        # make sure you load the correct model before.   
        print("# VAE fid")
        print("generating imgs for VAE fid ......")
        my_F.vae_generate_imgs(vae_model)
        print("calculating VAE fid ......")
        fid_vae = my_F.calcualte_fid("hw_train", "vae")
        val_fid_vae = my_F.calcualte_fid("hw_val", "vae")
        print("VAE fid_score: ", fid_vae)
        print("VAE val_fid_score: ", val_fid_vae)

        print("\n")

        print("# GAN fid")
        print("generating imgs for GAN fid ......")
        my_F.gans_generate_imgs(gan_g)
        print("calculating GAN fid ......")
        fid_gan = my_F.calcualte_fid("hw_train", "gans")
        val_fid_gan = my_F.calcualte_fid("hw_val", "gans")
        print("GAN fid_score: ", fid_gan)
        print("GAN val_fid_score: ", val_fid_gan)

        print("\n")

        print("# DDPM fid")
        print("generating imgs for DDPM_500 fid ......")
        # to save time, imgs of ddpm have been generated before, saved in the _FID_imgs: ddpm, so we do not need to run this
        #my_F.ddpm_generate_imgs(ddpm_model, diffuser, n_100=50,save_folder="_FID_imgs/ddpm")
        print("calculating DDPM_500 fid ......")
        fid_ddpm = my_F.calcualte_fid("cifar_train", "ddpm")
        val_fid_ddpm = my_F.calcualte_fid("cifar_test", "ddpm")
        print("DDPM 500_epoch fid_score: ", fid_ddpm)
        print("DDPM 500_epoch test_fid_score: ", val_fid_ddpm)


