import functions as my_F



# model_name = "_conditional_residual_attention_DDPM"
# save_path =  "_FID_ddpm_model_advanced"
# model, diffuser = my_F.load_ddpm_model(model_name, is_attention_on=True, is_residual_on=True,n_label=10)
# my_F.generate_imgs(model, diffuser, save_folder=save_path, n_label=10, n_100= 50)
# my_F.generate_gird_imgs(model, diffuser, n_label=10, modelname=model_name, epoch_index= 999)

# model_name = "vae"
# model = my_F.load_vae_model(model_name)
# my_F.vae_generate_imgs(model)

''' 

    this .py is implemented for demo.


'''

title_vae = """

GENERATED BY OUR VAE MODEL

"""


title_gans = """

GENERATED BY OUR GANs MODEL

"""

test_str_0 = """

COMP7015 Artificial Intelligence Group Project Instructions

Topic 3: Open Topic
If you are interested in another AI problem that aligns with the course content, 
you may propose your own project. 
This is an opportunity to explore areas like generative AI, multimodal learning, 
foundation models, or other advanced deep learning applications.
You are free to choose any relevant dataset and AI/deep learning methods.
Your project should demonstrate a clear understanding of the principles and techniques taught in this course.
Remember that the chosen topic's difficulty, scope, and creativity will be key factors in your evaluation.

Evaluation Criteria
Your project will be evaluated based on a holistic assessment of your work across several 
dimensions:
• Project Completeness & Model Performance: How thoroughly the project tasks were 
completed and the effectiveness of your final model(s) on the chosen task.
• Creativity & Difficulty: The novelty of your approach, the technical challenge of the 
problem, and the sophistication of the methods used.
• Code Quality: The readability, organization, and documentation of your source code. 
Clean and well-structured code is expected.
• Storytelling (Report & Presentation): The clarity and depth of your project report and 
presentation. This includes how well you explain your motivation, describe your 
methodology, analyze your results, and present your conclusions.
"""


test_Str = """
1234567890
1234567890
1234567890

ABCDEFGHIJKLMNOPQRSTUVwXYZ
abcdefghijklmnopqrstuvwxyz

Group:42  IMAGE GENERATIVE MODEL 

1: Zihao ZHAO    25418823
2: Bojie XIANG   25400444
3: Zinao SU      25434675
4: Tianchi ZHOU  25409638
5: Tianxiao ZHU  25407732

""" + test_str_0.upper() + test_str_0.lower()



if __name__ == '__main__':
    print("##### demo starts")
    print("\n")

    print("demo GAN")
    print("loading GANs model ......")
    model_name = "gans"
    gan_g, gan_d = my_F.load_gans_model(model_name,)
    print("generating GANs sample ......")
    my_F.gans_save_samples(gan_g, input_str=title_gans+test_Str,save_folder="demo_save")
    print("GAN samples saved in folder demo_save")

    # demo vae
    print("\n\n")
    print("demo VAE")
    model_name = "vae"
    print("loading VAE model ......")
    vae_model = my_F.load_vae_model(model_name)
    print("generating VAE samples ......")
    my_F.vae_save_samples(vae_model, input_str=title_vae+test_Str, save_folder="demo_save")
    print("VAE samples saved in folder demo_save")


    # demo ddpm
    print("\n\n")
    print("demo DDPM")
    print("loading DDPM model ......")
    model_name = "ddpm"
    model, diffuser = my_F.load_ddpm_model(model_name)
    print("generating DDPM samples ......")
    my_F.demo_addnoise(diffuser, save_folder="demo_save")
    my_F.demo_denoise(model, diffuser, save_folder="demo_save")
    my_F.ddpm_save_samples(model, diffuser, modelname="ddpm", save_folder="demo_save")
    print("DDPM samples saved in folder demo_save")

    print("\n\n")
    print("##### demo ends")

    #calculate FID
    # print("################")
    # print("calculating GANs FID")
    # my_F.save_hand_writing_images()
    # my_F.vae_generate_imgs(vae_model)
    # my_F.gans_generate_imgs(gan_g)

    # fid_gan = my_F.calcualte_fid("hw_train", "gans")
    # print("gan fid_score: ", fid_gan)
    # print("calculating VAE FID")
    # fid_vae = my_F.calcualte_fid("hw_train", "vae")
    # print("VAE fid_score: ", fid_vae)

    # print("###################demo ends")


# demo gans


# if __name__ == '__main__':
#     fid_1  = my_F.calcualte_fid("hw_train", "gans")
#     print(fid_1)
# my_F.save_hand_writing_images("hw_train")